// GENERATED by scripts/sync-editorial-index.mjs. Do not edit.
export const editorialGuides = [
  {
    "slug": "dorm-room-buying-checklist",
    "title": "How to Choose Dorm Room Essentials Without Overbuying",
    "description": "A room-first checklist for choosing dorm essentials by space, noise, outlets, upkeep, portability, and residence-hall rules.",
    "categorySlug": "dorm-room-essentials",
    "productSlugs": [
      "aroeve-mk06-air-purifier",
      "koonie-rechargeable-misting-fan",
      "myhalos-3d-blackout-sleep-mask",
      "chefman-1-8l-electric-kettle"
    ],
    "sourceUrls": [
      "https://www.ithaca.edu/office-residential-life/policies/appliances",
      "https://college.yale.edu/welcome-yale-college/new-student-faqs"
    ],
    "datePublished": "2026-08-31",
    "dateModified": "2026-08-31",
    "seo": {
      "primaryKeyword": "how to choose dorm room essentials",
      "secondaryKeywords": [
        "dorm room buying checklist",
        "college dorm appliance rules",
        "dorm essentials guide"
      ],
      "searchIntent": "informational",
      "pageType": "guide",
      "competitionNote": "Editorial seed based on approved source records.",
      "trendStatus": "unknown",
      "priority": 1
    },
    "questions": [
      {
        "question": "What should I buy first for a dorm room?",
        "answer": "Start with a problem you have confirmed in the actual room, then choose the smallest product that solves it without conflicting with housing rules or your roommate's needs."
      },
      {
        "question": "Are electric kettles allowed in dorm rooms?",
        "answer": "Rules vary by institution, building, and room type. Check the current written policy and ask housing staff when the wording is unclear."
      },
      {
        "question": "Should I buy a fan or an air purifier?",
        "answer": "Choose a fan for direct personal airflow and a purifier for particle filtration. Neither is a universal fix for building ventilation or temperature problems."
      }
    ]
  }
];
export const editorialReviews = [
  {
    "productSlug": "aroeve-mk06-air-purifier",
    "title": "AROEVE MK06 Air Purifier Review: Is the Small Format Dorm-Friendly?",
    "description": "An evidence-led look at the AROEVE MK06 size, sleep-mode claim, filter upkeep, evidence limits, and fit for a small dorm room.",
    "guideSlug": "dorm-room-buying-checklist",
    "decision": {
      "headline": "Consider it for compact particle filtration, not cooling, if its footprint and recurring filter upkeep fit your room and budget.",
      "bestFit": "Students who want a small purifier beside a desk or bed and are prepared to replace filters regularly.",
      "skipIf": "You need independently verified CADR for precise room sizing, want a cooling breeze, or do not want recurring filter costs."
    },
    "datePublished": "2026-08-31",
    "dateModified": "2026-08-31",
    "sourceUrls": [
      "https://aroeve.com/products/aroeve-air-purifiers-mk06",
      "https://www.amazon.com/dp/B0BN51YQ5X",
      "https://www.epa.gov/indoor-air-quality-iaq/air-cleaners-and-air-filters-home"
    ]
  },
  {
    "productSlug": "chefman-1-8l-electric-kettle",
    "title": "Chefman 1.8L Electric Kettle Review: Check Dorm Rules First",
    "description": "A decision-focused look at the Chefman kettle's 1.8-liter capacity, 1500-watt load, safety features, cleaning, and residence-policy fit.",
    "guideSlug": "dorm-room-buying-checklist",
    "decision": {
      "headline": "Buy only after your residence explicitly permits an automatic-shutoff kettle and the 1.8-liter, 1500-watt format fits your space.",
      "bestFit": "Students with written housing approval who want several cups of hot water and value automatic shutoff and boil-dry protection.",
      "skipIf": "Your residence prohibits kettles, limits high-wattage appliances, or a large glass kettle would crowd your available surface."
    },
    "datePublished": "2026-08-31",
    "dateModified": "2026-08-31",
    "sourceUrls": [
      "https://chefman.com/products/1-8l-stainless-steel-electric-kettle",
      "https://www.amazon.com/dp/B0C5Z8VCHX",
      "https://www.ithaca.edu/office-residential-life/policies/appliances"
    ]
  },
  {
    "productSlug": "koonie-rechargeable-misting-fan",
    "title": "Koonie Rechargeable Misting Fan Review: Useful for a Dorm Desk?",
    "description": "A practical look at the Koonie 8-inch fan's clip-and-desk format, rechargeable battery, mist upkeep, placement, and dorm-room tradeoffs.",
    "guideSlug": "dorm-room-buying-checklist",
    "decision": {
      "headline": "Consider it for flexible personal airflow where outlets are awkward; treat the mist feature as optional upkeep, not automatic value.",
      "bestFit": "Students who want a rechargeable desk-or-clip fan for a bed or study area and can manage charging and water safely.",
      "skipIf": "You expect whole-room cooling, dislike tank cleaning, or have no stable, spill-conscious place for indoor mist."
    },
    "datePublished": "2026-08-31",
    "dateModified": "2026-08-31",
    "sourceUrls": [
      "https://docs.partnerboost.com/developers/publisher-api/amazon/",
      "https://www.amazon.com/dp/B0DS25SXZ3"
    ]
  },
  {
    "productSlug": "myhalos-3d-blackout-sleep-mask",
    "title": "MyHalos 3D Blackout Sleep Mask Review: A Practical Dorm Option?",
    "description": "An evidence-led review of the MyHalos mask's contoured shape, adjustable fit, hand-wash care, and limits as a dorm light-control tool.",
    "guideSlug": "dorm-room-buying-checklist",
    "decision": {
      "headline": "Consider it when unwanted light is the specific sleep-environment problem and you prefer a contoured mask with adjustable fit.",
      "bestFit": "Students dealing with roommate lamps, hallway light, bright windows, or schedule mismatch who want a portable light barrier.",
      "skipIf": "You dislike head straps, need machine-wash convenience, or expect one mask to solve noise, heat, stress, or a disrupted schedule."
    },
    "datePublished": "2026-08-31",
    "dateModified": "2026-08-31",
    "sourceUrls": [
      "https://myhalos.com/products/blackout-sleep-mask",
      "https://www.amazon.com/dp/B09CZ68WV3",
      "https://www.cdc.gov/niosh/bulletin/2020/sleep.html"
    ]
  }
];
